CREATE TABLE IF NOT EXISTS orders (
    id VARCHAR PRIMARY KEY NOT NULL,
    product_id VARCHAR REFERENCES products(id) ON DELETE CASCADE,
    user_id VARCHAR REFERENCES users(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL
);